# Generated by Django 4.2.2 on 2023-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=200)),
            ],
        ),
    ]
