# Generated by Django 3.0.7 on 2023-05-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0002_auto_20230527_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
