# Generated by Django 4.2.2 on 2023-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_auth", "0003_auto_20230528_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
